// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwwhPH2qlFdtAIbYXvYpIfQy--DbTLMXw',
    appId: '1:179342288564:web:9f846c89bc590e792cd9e1',
    messagingSenderId: '179342288564',
    projectId: 'social-app-92f4f',
    authDomain: 'social-app-92f4f.firebaseapp.com',
    storageBucket: 'social-app-92f4f.appspot.com',
    measurementId: 'G-FHDMLS2Q07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCojqX1R7FfcgC-3koofsTfTzhKXNxtWEU',
    appId: '1:179342288564:android:c75476fa395d07272cd9e1',
    messagingSenderId: '179342288564',
    projectId: 'social-app-92f4f',
    storageBucket: 'social-app-92f4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVa9n4oOm6ITGHVm348bQyhYhAhktjpJY',
    appId: '1:179342288564:ios:75948050c86375712cd9e1',
    messagingSenderId: '179342288564',
    projectId: 'social-app-92f4f',
    storageBucket: 'social-app-92f4f.appspot.com',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVa9n4oOm6ITGHVm348bQyhYhAhktjpJY',
    appId: '1:179342288564:ios:75948050c86375712cd9e1',
    messagingSenderId: '179342288564',
    projectId: 'social-app-92f4f',
    storageBucket: 'social-app-92f4f.appspot.com',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwwhPH2qlFdtAIbYXvYpIfQy--DbTLMXw',
    appId: '1:179342288564:web:bef6f9599055b0772cd9e1',
    messagingSenderId: '179342288564',
    projectId: 'social-app-92f4f',
    authDomain: 'social-app-92f4f.firebaseapp.com',
    storageBucket: 'social-app-92f4f.appspot.com',
    measurementId: 'G-D4611X9JNR',
  );
}
